# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.11.7
  - 2.10.5
  - 2.9.3
# Branches to test
branches:
  only:
    - master
    - 2.7.x
notifications:
  email:
    recipients:
      - ross@mongodb.com
      - jeff.yemin@mongodb.com
    on_success: change
    on_failure: always
  flowdock:
    secure: "gR8a3oaAa9+ww2xfCp9dYysF/gAQCyWpG5R+Ms0QkQBUStmlhnszHelio67/xcVjHaTDf/t+ocGUbL95v8ruMVer1QOUV0NMrUSYFUwzjjXDg3TpwEO48psEu2gfsgUuL2GW0f/OMaIfUXVccu8pAXrKVCMnu0xR6NaJEkZo/Sk="
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
services:
  - mongodb
