# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.3
  - 2.9.3
# Branches to test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - ross@mongodb.com
      - jeff.yemin@mongodb.com
    on_success: change
    on_failure: always
  flowdock:
    secure: "Ziw1Be2tV0QAYuiYDrepfdNH/oBfNhnXFMji3AdRi6MePVpc6CtOOT/b9Fra\nQgMMrX3AHk/QIDo6QQx9/aVB3FS1fzOPGQkSsEZmiljZU7wZCct1sSSyttf/\nsRG0lyTnmgFNTHyTSDT3JbXAkyF/vJmG/JJJoBUZhmFxzR2fM0Q="
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
services:
  - mongodb
